# Generated by Django 5.0 on 2024-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'About_model',
                'verbose_name_plural': 'About_models',
            },
        ),
        migrations.CreateModel(
            name='Backround_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Backround_image/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Backround_image',
                'verbose_name_plural': 'Backround_images',
            },
        ),
    ]
